import type { Citation } from '@/lib/history';

/**
 * Generated by deduping every citation used on the page, so it can't drift
 * from the claims above it — adding a fact adds its source here automatically,
 * and removing one removes it.
 */
export default function SourceList({ sources }: { sources: Citation[] }) {
  return (
    <ul className="font-mono text-[11px] uppercase tracking-[0.08em] space-y-1.5">
      {sources.map(s => (
        <li key={s.href}>
          <a
            href={s.href}
            target="_blank"
            rel="noopener noreferrer"
            className="text-bone-dim hover:text-bone underline underline-offset-4"
          >
            {s.label} ↗
          </a>
        </li>
      ))}
    </ul>
  );
}
